# Generated by Django 4.0.2 on 2022-02-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
    ]
