# Generated by Django 4.0.2 on 2022-02-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
