# Generated by Django 4.0.2 on 2022-02-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
        ('data_handler', '0003_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_upload.file'),
            preserve_default=False,
        ),
    ]
